namespace NativeEngine
{
	[Flags]
	internal enum SceneViewFlags
	{
		SVF_DEBUG_LAYERS,
		SVF_TOOL_VIEW,
		SVF_CAN_ALLOCATE_RENDER_TARGETS_IN_DEV,
		SVF_ENABLE_VR_RENDERING,
		SVF_HAMMER_VIEW,
		SVF_IS_LIGHT_SHADOW_VIEW,
		SVF_DISABLE_ALPHA_FADE,
		SVF_ORTHOGRAPHIC,
		SVF_WIREFRAME,
		SVF_SKIP_FRUSTUM_CULL,
		SVF_MONITOR_VIEW,
		SVF_NO_TEXTURE_STREAMING,

		SVF_FIRST_UNUSED_FLAG,
	}

	internal enum SceneLayerMSAAMode_t
	{
		Off = 0,
		On = 1
	}
}
